// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Prisma CLI(migrate 등)는 unpooled(direct) 연결이 필요 — 앱 런타임의 pooled DATABASE_URL과는 다른 값.
  datasource: {
    url: process.env["DIRECT_DATABASE_URL"],
  },
});
